"""SQLite schema for replay-first persistence plus additive research storage."""

from sqlalchemy import (
    Boolean,
    Column,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    Table,
    Text,
    UniqueConstraint,
)

from .db import metadata

NUMERIC_TYPE = Numeric(24, 10, asdecimal=True)

PERSISTENCE_TABLES = (
    "instruments",
    "bars",
    "features",
    "signals",
    "derived_features",
    "signal_evaluations",
    "trade_outcomes",
    "experiment_runs",
    "strategy_state_snapshots",
    "order_intents",
    "fills",
    "alert_events",
    "reconciliation_events",
    "fault_events",
    "processed_bars",
    "research_capture_runs",
    "research_capture_status",
)

instruments_table = Table(
    "instruments",
    metadata,
    Column("instrument_id", Integer, primary_key=True, autoincrement=True),
    Column("ticker", Text, nullable=False),
    Column("cusip", Text, nullable=True),
    Column("asset_class", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("exchange", Text, nullable=True),
    Column("multiplier", NUMERIC_TYPE, nullable=True),
    Column("is_active", Boolean, nullable=False, default=True),
    UniqueConstraint("ticker", "asset_class", name="uq_instruments_ticker_asset_class"),
    Index("ix_instruments_ticker", "ticker"),
)

bars_table = Table(
    "bars",
    metadata,
    Column("bar_id", Text, primary_key=True),
    Column("instrument_id", Integer, ForeignKey("instruments.instrument_id"), nullable=True, index=True),
    Column("ticker", Text, nullable=False, index=True),
    Column("cusip", Text, nullable=True),
    Column("asset_class", Text, nullable=True),
    Column("data_source", Text, nullable=False, default="internal"),
    Column("timestamp", Text, nullable=False, index=True),
    Column("symbol", Text, nullable=False),
    Column("timeframe", Text, nullable=False),
    Column("start_ts", Text, nullable=False),
    Column("end_ts", Text, nullable=False, index=True),
    Column("open", NUMERIC_TYPE, nullable=False),
    Column("high", NUMERIC_TYPE, nullable=False),
    Column("low", NUMERIC_TYPE, nullable=False),
    Column("close", NUMERIC_TYPE, nullable=False),
    Column("volume", Integer, nullable=False),
    Column("is_final", Boolean, nullable=False),
    Column("session_asia", Boolean, nullable=False),
    Column("session_london", Boolean, nullable=False),
    Column("session_us", Boolean, nullable=False),
    Column("session_allowed", Boolean, nullable=False),
    Column("created_at", Text, nullable=False),
    UniqueConstraint("ticker", "timeframe", "timestamp", "data_source", name="uq_bars_identity"),
    Index("ix_bars_lookup", "ticker", "timeframe", "timestamp"),
)

features_table = Table(
    "features",
    metadata,
    Column("bar_id", Text, primary_key=True),
    Column("payload_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
)

signals_table = Table(
    "signals",
    metadata,
    Column("bar_id", Text, primary_key=True),
    Column("payload_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
)

experiment_runs_table = Table(
    "experiment_runs",
    metadata,
    Column("experiment_run_id", Integer, primary_key=True, autoincrement=True),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("market_universe", Text, nullable=True),
    Column("timeframe", Text, nullable=True),
    Column("feature_version", Text, nullable=True),
    Column("signal_version", Text, nullable=True),
    Column("sizing_version", Text, nullable=True),
    Column("config_json", Text, nullable=True),
    Column("started_at", Text, nullable=False, index=True),
    Column("completed_at", Text, nullable=True),
)

derived_features_table = Table(
    "derived_features",
    metadata,
    Column("feature_id", Integer, primary_key=True, autoincrement=True),
    Column("bar_id", Text, ForeignKey("bars.bar_id"), nullable=False, index=True),
    Column("experiment_run_id", Integer, ForeignKey("experiment_runs.experiment_run_id"), nullable=True, index=True),
    Column("atr", NUMERIC_TYPE, nullable=True),
    Column("vwap", NUMERIC_TYPE, nullable=True),
    Column("ema_fast", NUMERIC_TYPE, nullable=True),
    Column("ema_slow", NUMERIC_TYPE, nullable=True),
    Column("velocity", NUMERIC_TYPE, nullable=True),
    Column("velocity_delta", NUMERIC_TYPE, nullable=True),
    Column("stretch_down", NUMERIC_TYPE, nullable=True),
    Column("stretch_up", NUMERIC_TYPE, nullable=True),
    Column("smoothed_close", NUMERIC_TYPE, nullable=True),
    Column("momentum_raw", NUMERIC_TYPE, nullable=True),
    Column("momentum_norm", NUMERIC_TYPE, nullable=True),
    Column("momentum_delta", NUMERIC_TYPE, nullable=True),
    Column("momentum_acceleration", NUMERIC_TYPE, nullable=True),
    Column("volume_ratio", NUMERIC_TYPE, nullable=True),
    Column("signed_impulse", NUMERIC_TYPE, nullable=True),
    Column("smoothed_signed_impulse", NUMERIC_TYPE, nullable=True),
    Column("impulse_delta", NUMERIC_TYPE, nullable=True),
    Column("created_at", Text, nullable=False, index=True),
    UniqueConstraint("bar_id", "experiment_run_id", name="uq_derived_features_bar_run"),
)

signal_evaluations_table = Table(
    "signal_evaluations",
    metadata,
    Column("signal_eval_id", Integer, primary_key=True, autoincrement=True),
    Column("bar_id", Text, ForeignKey("bars.bar_id"), nullable=False, index=True),
    Column("experiment_run_id", Integer, ForeignKey("experiment_runs.experiment_run_id"), nullable=False, index=True),
    Column("bull_snap_raw", Boolean, nullable=False),
    Column("bear_snap_raw", Boolean, nullable=False),
    Column("asia_vwap_reclaim_raw", Boolean, nullable=False),
    Column("momentum_compressing_up", Boolean, nullable=False),
    Column("momentum_turning_positive", Boolean, nullable=False),
    Column("momentum_compressing_down", Boolean, nullable=False),
    Column("momentum_turning_negative", Boolean, nullable=False),
    Column("filter_pass_long", Boolean, nullable=False),
    Column("filter_pass_short", Boolean, nullable=False),
    Column("trigger_long_math", Boolean, nullable=False),
    Column("trigger_short_math", Boolean, nullable=False),
    Column("warmup_complete", Boolean, nullable=False, default=False),
    Column("compression_long", Boolean, nullable=False, default=False),
    Column("reclaim_long", Boolean, nullable=False, default=False),
    Column("separation_long", Boolean, nullable=False, default=False),
    Column("structure_long_candidate", Boolean, nullable=False, default=False),
    Column("compression_short", Boolean, nullable=False, default=False),
    Column("failure_short", Boolean, nullable=False, default=False),
    Column("separation_short", Boolean, nullable=False, default=False),
    Column("structure_short_candidate", Boolean, nullable=False, default=False),
    Column("quality_score_long", NUMERIC_TYPE, nullable=True),
    Column("quality_score_short", NUMERIC_TYPE, nullable=True),
    Column("size_recommendation_long", NUMERIC_TYPE, nullable=True),
    Column("size_recommendation_short", NUMERIC_TYPE, nullable=True),
    Column("created_at", Text, nullable=False, index=True),
    UniqueConstraint("bar_id", "experiment_run_id", name="uq_signal_evaluations_bar_run"),
)

trade_outcomes_table = Table(
    "trade_outcomes",
    metadata,
    Column("trade_id", Integer, primary_key=True, autoincrement=True),
    Column("experiment_run_id", Integer, ForeignKey("experiment_runs.experiment_run_id"), nullable=False, index=True),
    Column("entry_bar_id", Text, ForeignKey("bars.bar_id"), nullable=False, index=True),
    Column("exit_bar_id", Text, ForeignKey("bars.bar_id"), nullable=True, index=True),
    Column("ticker", Text, nullable=False, index=True),
    Column("timeframe", Text, nullable=False),
    Column("side", Text, nullable=False),
    Column("entry_family", Text, nullable=True),
    Column("entry_reason", Text, nullable=False),
    Column("entry_price", NUMERIC_TYPE, nullable=False),
    Column("exit_price", NUMERIC_TYPE, nullable=True),
    Column("size", NUMERIC_TYPE, nullable=False),
    Column("bars_held", Integer, nullable=True),
    Column("pnl", NUMERIC_TYPE, nullable=True),
    Column("mae", NUMERIC_TYPE, nullable=True),
    Column("mfe", NUMERIC_TYPE, nullable=True),
    Column("exit_reason", Text, nullable=True),
    Column("quality_score_at_entry", NUMERIC_TYPE, nullable=True),
    Column("size_recommendation_at_entry", NUMERIC_TYPE, nullable=True),
    Column("created_at", Text, nullable=False, index=True),
)

strategy_state_snapshots_table = Table(
    "strategy_state_snapshots",
    metadata,
    Column("snapshot_id", Integer, primary_key=True, autoincrement=True),
    Column("standalone_strategy_id", Text, nullable=True, index=True),
    Column("strategy_family", Text, nullable=True),
    Column("instrument", Text, nullable=True, index=True),
    Column("lane_id", Text, nullable=True, index=True),
    Column("updated_at", Text, nullable=False, index=True),
    Column("strategy_status", Text, nullable=False),
    Column("position_side", Text, nullable=False),
    Column("long_entry_family", Text, nullable=False),
    Column("transition_label", Text, nullable=True),
    Column("payload_json", Text, nullable=False),
)

order_intents_table = Table(
    "order_intents",
    metadata,
    Column("order_intent_id", Text, primary_key=True),
    Column("standalone_strategy_id", Text, nullable=True, index=True),
    Column("strategy_family", Text, nullable=True),
    Column("instrument", Text, nullable=True, index=True),
    Column("lane_id", Text, nullable=True, index=True),
    Column("bar_id", Text, nullable=False, index=True),
    Column("symbol", Text, nullable=False),
    Column("intent_type", Text, nullable=False),
    Column("quantity", Integer, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("submitted_at", Text, nullable=True),
    Column("acknowledged_at", Text, nullable=True),
    Column("reason_code", Text, nullable=False),
    Column("broker_order_id", Text, nullable=True),
    Column("order_status", Text, nullable=False),
    Column("broker_order_status", Text, nullable=True),
    Column("last_status_checked_at", Text, nullable=True),
    Column("timeout_classification", Text, nullable=True),
    Column("timeout_status_updated_at", Text, nullable=True),
    Column("retry_count", Integer, nullable=False, default=0),
)

fills_table = Table(
    "fills",
    metadata,
    Column("fill_id", Integer, primary_key=True, autoincrement=True),
    Column("standalone_strategy_id", Text, nullable=True, index=True),
    Column("strategy_family", Text, nullable=True),
    Column("instrument", Text, nullable=True, index=True),
    Column("lane_id", Text, nullable=True, index=True),
    Column("order_intent_id", Text, nullable=False, index=True),
    Column("intent_type", Text, nullable=False),
    Column("order_status", Text, nullable=False),
    Column("fill_timestamp", Text, nullable=False, index=True),
    Column("fill_price", Text, nullable=True),
    Column("broker_order_id", Text, nullable=True),
)

alert_events_table = Table(
    "alert_events",
    metadata,
    Column("alert_id", Integer, primary_key=True, autoincrement=True),
    Column("occurred_at", Text, nullable=False, index=True),
    Column("category", Text, nullable=False, index=True),
    Column("severity", Text, nullable=False, index=True),
    Column("title", Text, nullable=False),
    Column("message", Text, nullable=False),
    Column("source_subsystem", Text, nullable=False, index=True),
    Column("dedup_key", Text, nullable=True, index=True),
    Column("active", Boolean, nullable=False, default=False, index=True),
    Column("acknowledged", Boolean, nullable=False, default=False, index=True),
    Column("payload_json", Text, nullable=False),
)

reconciliation_events_table = Table(
    "reconciliation_events",
    metadata,
    Column("event_id", Integer, primary_key=True, autoincrement=True),
    Column("created_at", Text, nullable=False),
    Column("payload_json", Text, nullable=False),
)

execution_watchdog_events_table = Table(
    "execution_watchdog_events",
    metadata,
    Column("event_id", Integer, primary_key=True, autoincrement=True),
    Column("created_at", Text, nullable=False, index=True),
    Column("payload_json", Text, nullable=False),
)

fault_events_table = Table(
    "fault_events",
    metadata,
    Column("event_id", Integer, primary_key=True, autoincrement=True),
    Column("created_at", Text, nullable=False),
    Column("bar_id", Text, nullable=True),
    Column("fault_code", Text, nullable=False),
    Column("payload_json", Text, nullable=False),
)

processed_bars_table = Table(
    "processed_bars",
    metadata,
    Column("bar_id", Text, primary_key=True),
    Column("standalone_strategy_id", Text, nullable=True, index=True),
    Column("instrument", Text, nullable=True, index=True),
    Column("lane_id", Text, nullable=True, index=True),
    Column("end_ts", Text, nullable=False, index=True),
)

research_capture_runs_table = Table(
    "research_capture_runs",
    metadata,
    Column("capture_run_id", Integer, primary_key=True, autoincrement=True),
    Column("symbol", Text, nullable=False, index=True),
    Column("timeframe", Text, nullable=False, index=True),
    Column("capture_class", Text, nullable=False, index=True),
    Column("data_source", Text, nullable=False, index=True),
    Column("started_at", Text, nullable=False, index=True),
    Column("completed_at", Text, nullable=True, index=True),
    Column("status", Text, nullable=False, index=True),
    Column("previous_last_bar_end_ts", Text, nullable=True),
    Column("fetched_bar_count", Integer, nullable=False, default=0),
    Column("fetched_first_bar_end_ts", Text, nullable=True),
    Column("fetched_last_bar_end_ts", Text, nullable=True),
    Column("persisted_last_bar_end_ts", Text, nullable=True),
    Column("failure_code", Text, nullable=True),
    Column("failure_detail", Text, nullable=True),
)

research_capture_status_table = Table(
    "research_capture_status",
    metadata,
    Column("symbol", Text, nullable=False),
    Column("timeframe", Text, nullable=False),
    Column("capture_class", Text, nullable=False),
    Column("data_source", Text, nullable=False),
    Column("last_attempted_at", Text, nullable=False, index=True),
    Column("last_succeeded_at", Text, nullable=True, index=True),
    Column("last_bar_end_ts", Text, nullable=True, index=True),
    Column("last_status", Text, nullable=False, index=True),
    Column("last_failure_code", Text, nullable=True),
    Column("last_failure_detail", Text, nullable=True),
    Column("last_capture_run_id", Integer, nullable=True),
    UniqueConstraint(
        "symbol",
        "timeframe",
        "capture_class",
        "data_source",
        name="uq_research_capture_status_identity",
    ),
)
