"""Settings-model tests for the Phase 3A blueprint."""

from datetime import time
from decimal import Decimal

from mgc_v05l.domain.enums import ReplayFillPolicy, VwapPolicy
from mgc_v05l.config_models.settings import RuntimeMode, StrategySettings


def test_strategy_settings_enforce_locked_runtime_values() -> None:
    settings = StrategySettings(
        symbol="MGC",
        timeframe="5m",
        timezone="America/New_York",
        mode=RuntimeMode.REPLAY,
        database_url="sqlite:///./mgc_v05l.sqlite3",
        replay_fill_policy=ReplayFillPolicy.NEXT_BAR_OPEN,
        vwap_policy=VwapPolicy.SESSION_RESET,
        trade_size=1,
        enable_bull_snap_longs=True,
        enable_bear_snap_shorts=True,
        enable_asia_vwap_longs=True,
        atr_len=14,
        stop_atr_mult=Decimal("1.5"),
        breakeven_at_r=Decimal("1.0"),
        max_bars_long=20,
        max_bars_short=20,
        allow_asia=True,
        allow_london=True,
        allow_us=True,
        asia_start=time(18, 0),
        asia_end=time(23, 0),
        london_start=time(0, 0),
        london_end=time(6, 0),
        us_start=time(8, 30),
        us_end=time(16, 0),
        anti_churn_bars=3,
        use_turn_family=True,
        turn_fast_len=5,
        turn_slow_len=13,
        turn_signal_len=9,
        turn_stretch_lookback=8,
        min_snap_down_stretch_atr=Decimal("1.0"),
        min_snap_bar_range_atr=Decimal("0.5"),
        min_snap_body_atr=Decimal("0.25"),
        min_snap_close_location=Decimal("0.7"),
        min_snap_velocity_delta_atr=Decimal("0.1"),
        snap_cooldown_bars=4,
        use_asia_bull_snap_thresholds=True,
        asia_min_snap_bar_range_atr=Decimal("0.4"),
        asia_min_snap_body_atr=Decimal("0.2"),
        asia_min_snap_velocity_delta_atr=Decimal("0.08"),
        use_bull_snap_location_filter=True,
        bull_snap_max_close_vs_slow_ema_atr=Decimal("0.5"),
        bull_snap_require_close_below_slow_ema=True,
        min_bear_snap_up_stretch_atr=Decimal("1.0"),
        min_bear_snap_bar_range_atr=Decimal("0.5"),
        min_bear_snap_body_atr=Decimal("0.25"),
        max_bear_snap_close_location=Decimal("0.3"),
        min_bear_snap_velocity_delta_atr=Decimal("0.1"),
        bear_snap_cooldown_bars=4,
        use_bear_snap_location_filter=True,
        bear_snap_min_close_vs_slow_ema_atr=Decimal("0.5"),
        bear_snap_require_close_above_slow_ema=True,
        below_vwap_lookback=6,
        require_green_reclaim_bar=True,
        reclaim_close_buffer_atr=Decimal("0.05"),
        min_vwap_bar_range_atr=Decimal("0.4"),
        use_vwap_volume_filter=True,
        min_vwap_vol_ratio=Decimal("1.1"),
        require_hold_close_above_vwap=True,
        require_hold_not_break_reclaim_low=True,
        require_acceptance_close_above_reclaim_high=True,
        require_acceptance_close_above_vwap=True,
        vwap_long_stop_atr_mult=Decimal("1.2"),
        vwap_long_breakeven_at_r=Decimal("0.8"),
        vwap_long_max_bars=12,
        use_vwap_hard_loss_exit=True,
        vwap_weak_close_lookback_bars=3,
        vol_len=20,
        show_debug_labels=False,
    )

    assert settings.mode is RuntimeMode.REPLAY
    assert settings.warmup_bars_required() == 20
